"""Seed data for Edu-AI Core platform."""

COURSES = [
    {
        "id": "python-codewithharry",
        "title": "Python Tutorial for Beginners",
        "instructor": "CodeWithHarry",
        "category": "Programming",
        "level": "Beginner",
        "duration_hours": 12,
        "rating": 4.9,
        "enrolled": 184320,
        "thumbnail": "https://i.ytimg.com/vi/UrsmFxEIp5k/maxresdefault.jpg",
        "description": "Master Python from absolute scratch. Variables, data types, OOP, file handling, modules, and real projects — all in one playlist.",
        "playlist_id": "PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME",
        "lessons": [
            {"id": "p1", "title": "Introduction to Python", "video_id": "UrsmFxEIp5k", "duration": "12:34"},
            {"id": "p2", "title": "Variables, Data Types & Operators", "video_id": "ihk_Xglr164", "duration": "18:21"},
            {"id": "p3", "title": "Strings, Lists & Tuples in Python", "video_id": "y7-ON-Lpx7Y", "duration": "22:09"},
            {"id": "p4", "title": "Conditional Statements & Loops", "video_id": "VApXwL3hYHk", "duration": "19:47"},
            {"id": "p5", "title": "Functions & Recursion", "video_id": "8Yj_YV4DfQ4", "duration": "24:55"},
            {"id": "p6", "title": "Object Oriented Programming in Python", "video_id": "qiSCMNBIP2g", "duration": "31:12"},
        ],
    },
    {
        "id": "javascript-codewithharry",
        "title": "JavaScript Full Course",
        "instructor": "CodeWithHarry",
        "category": "Programming",
        "level": "Beginner",
        "duration_hours": 10,
        "rating": 4.8,
        "enrolled": 152011,
        "thumbnail": "https://i.ytimg.com/vi/htznIaDHgnA/maxresdefault.jpg",
        "description": "Become a JavaScript pro. From DOM manipulation to async/await, build modern web apps with confidence.",
        "playlist_id": "PLu0W_9lII9ahR1blWXxgSlL4y9iQwt-uy",
        "lessons": [
            {"id": "j1", "title": "Introduction to JavaScript", "video_id": "htznIaDHgnA", "duration": "15:02"},
            {"id": "j2", "title": "Variables, let, const & Scope", "video_id": "8KGS-Lj3iZ4", "duration": "17:45"},
            {"id": "j3", "title": "Functions & Arrow Functions", "video_id": "iypoodXcz0k", "duration": "20:18"},
            {"id": "j4", "title": "DOM Manipulation Basics", "video_id": "5fb2aPlgoys", "duration": "26:30"},
            {"id": "j5", "title": "Async, Promises & Fetch API", "video_id": "Pubd-spHN-0", "duration": "28:14"},
            {"id": "j6", "title": "ES6+ Features & Mini Project", "video_id": "ZrQuKw-Ulm4", "duration": "33:48"},
        ],
    },
    {
        "id": "react-codewithharry",
        "title": "React JS Course for Beginners",
        "instructor": "CodeWithHarry",
        "category": "Web Development",
        "level": "Intermediate",
        "duration_hours": 9,
        "rating": 4.9,
        "enrolled": 98432,
        "thumbnail": "https://i.ytimg.com/vi/RGKi6LSPDLU/maxresdefault.jpg",
        "description": "Build modern UIs with React. Components, hooks, state, routing, and a complete project walkthrough.",
        "playlist_id": "PLu0W_9lII9agx66oZnT6IyhcMIbUMNMdt",
        "lessons": [
            {"id": "r1", "title": "Introduction to React JS", "video_id": "RGKi6LSPDLU", "duration": "11:23"},
            {"id": "r2", "title": "JSX, Components & Props", "video_id": "dGcsHMXbSOA", "duration": "19:55"},
            {"id": "r3", "title": "useState & Event Handling", "video_id": "AAJB6mpJSOA", "duration": "22:40"},
            {"id": "r4", "title": "useEffect & Side Effects", "video_id": "0fYi8SGA20k", "duration": "24:11"},
            {"id": "r5", "title": "React Router & Navigation", "video_id": "yQbB2WEbVjM", "duration": "21:08"},
            {"id": "r6", "title": "Building a Mini Project", "video_id": "QFaFIcGhPoM", "duration": "35:30"},
        ],
    },
    {
        "id": "datastructures-apnacollege",
        "title": "Data Structures & Algorithms",
        "instructor": "Apna College",
        "category": "Computer Science",
        "level": "Intermediate",
        "duration_hours": 18,
        "rating": 4.9,
        "enrolled": 211045,
        "thumbnail": "https://i.ytimg.com/vi/z9bZufPHFLU/maxresdefault.jpg",
        "description": "Comprehensive DSA course in C++/Java. Crack coding interviews with confidence using time-tested strategies.",
        "playlist_id": "PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt",
        "lessons": [
            {"id": "d1", "title": "Introduction to DSA", "video_id": "z9bZufPHFLU", "duration": "14:12"},
            {"id": "d2", "title": "Arrays & Time Complexity", "video_id": "37E9ckMDdTk", "duration": "26:33"},
            {"id": "d3", "title": "Linked Lists Mastery", "video_id": "70tx7KcMROc", "duration": "32:21"},
            {"id": "d4", "title": "Stacks, Queues & Recursion", "video_id": "rRItUKWFP6Y", "duration": "29:45"},
            {"id": "d5", "title": "Trees & Binary Search Trees", "video_id": "rcOOpSwasRk", "duration": "38:19"},
            {"id": "d6", "title": "Graphs, BFS & DFS", "video_id": "M3_pLsDdeuU", "duration": "41:02"},
        ],
    },
    {
        "id": "machinelearning-krishnaik",
        "title": "Complete Machine Learning Course",
        "instructor": "Krish Naik",
        "category": "Data Science",
        "level": "Advanced",
        "duration_hours": 22,
        "rating": 4.7,
        "enrolled": 76210,
        "thumbnail": "https://i.ytimg.com/vi/JxgmHe2NyeY/maxresdefault.jpg",
        "description": "End-to-end ML — supervised, unsupervised, deep learning, and deployment. Built for production-ready data scientists.",
        "playlist_id": "PLZoTAELRMXVPBTrWtJkn3wWQxZkmTXGwe",
        "lessons": [
            {"id": "m1", "title": "Introduction to Machine Learning", "video_id": "JxgmHe2NyeY", "duration": "16:42"},
            {"id": "m2", "title": "Linear Regression Explained", "video_id": "1NxnPkZM9bc", "duration": "28:15"},
            {"id": "m3", "title": "Logistic Regression & Classification", "video_id": "L_xBe7MbPwk", "duration": "31:20"},
            {"id": "m4", "title": "Decision Trees & Random Forest", "video_id": "nxC1iKnP8M4", "duration": "36:45"},
            {"id": "m5", "title": "Neural Networks Fundamentals", "video_id": "aircAruvnKk", "duration": "29:11"},
            {"id": "m6", "title": "Model Deployment with Flask", "video_id": "MxJnR1DMmsY", "duration": "33:50"},
        ],
    },
    {
        "id": "webdev-codewithharry",
        "title": "Full Stack Web Development",
        "instructor": "CodeWithHarry",
        "category": "Web Development",
        "level": "Beginner",
        "duration_hours": 16,
        "rating": 4.8,
        "enrolled": 142090,
        "thumbnail": "https://i.ytimg.com/vi/tVzUXW6siu0/maxresdefault.jpg",
        "description": "HTML, CSS, JavaScript, Node.js & MongoDB — build, deploy, and ship real web apps from day one.",
        "playlist_id": "PLu0W_9lII9ai6fAMHp-acBmJONT7Y4BSG",
        "lessons": [
            {"id": "w1", "title": "HTML Crash Course", "video_id": "BsDoLVMnmZs", "duration": "20:11"},
            {"id": "w2", "title": "CSS — Selectors, Flexbox, Grid", "video_id": "Edsxf_NBFrw", "duration": "27:33"},
            {"id": "w3", "title": "Responsive Design with Media Queries", "video_id": "ZYV6dYtz4HA", "duration": "22:45"},
            {"id": "w4", "title": "Backend with Node.js & Express", "video_id": "BLl32FvcdVM", "duration": "35:12"},
            {"id": "w5", "title": "MongoDB & Mongoose Essentials", "video_id": "ofme2o29ngU", "duration": "29:40"},
            {"id": "w6", "title": "Deploying Full-Stack Apps", "video_id": "l134cBAJCuc", "duration": "24:55"},
        ],
    },
]

JOBS = [
    {
        "id": "job-1",
        "title": "Junior Python Developer",
        "company": "Zoho Corporation",
        "location": "Chennai, India · Hybrid",
        "salary": "₹6 – 10 LPA",
        "type": "Full-time",
        "experience": "0-2 years",
        "posted": "2 days ago",
        "logo": "https://logo.clearbit.com/zoho.com",
        "description": "Build scalable backend services for our SaaS suite. Work with FastAPI, PostgreSQL, and Redis on systems serving 80M+ users worldwide.",
        "skills": ["Python", "FastAPI", "PostgreSQL", "Git", "REST APIs"],
        "requirements": [
            "Strong Python fundamentals & OOP",
            "Familiarity with at least one web framework",
            "Understanding of SQL and database design",
            "Bachelor's in CS or equivalent practical experience",
        ],
        "apply_url": "#",
    },
    {
        "id": "job-2",
        "title": "Frontend Engineer (React)",
        "company": "Razorpay",
        "location": "Bengaluru, India · Remote",
        "salary": "₹14 – 22 LPA",
        "type": "Full-time",
        "experience": "1-3 years",
        "posted": "5 days ago",
        "logo": "https://logo.clearbit.com/razorpay.com",
        "description": "Craft delightful payment experiences trusted by 10M+ businesses. Own complex UI flows in React and TypeScript end-to-end.",
        "skills": ["React", "TypeScript", "Tailwind CSS", "Jest", "GraphQL"],
        "requirements": [
            "2+ years building production React apps",
            "Solid grasp of state management & hooks",
            "Eye for pixel-perfect UI",
            "Comfortable owning features end-to-end",
        ],
        "apply_url": "#",
    },
    {
        "id": "job-3",
        "title": "Machine Learning Intern",
        "company": "Swiggy",
        "location": "Bengaluru, India · On-site",
        "salary": "₹60,000/month stipend",
        "type": "Internship · 6 months",
        "experience": "Final year students",
        "posted": "1 week ago",
        "logo": "https://logo.clearbit.com/swiggy.com",
        "description": "Help build ML models powering food recommendations, demand forecasting, and routing for India's largest food-tech platform.",
        "skills": ["Python", "scikit-learn", "PyTorch", "SQL", "Statistics"],
        "requirements": [
            "Pursuing B.Tech/M.Tech/PhD in CS or related",
            "Hands-on with ML projects on GitHub/Kaggle",
            "Solid math foundations (linear algebra, probability)",
            "Available for a 6-month full-time internship",
        ],
        "apply_url": "#",
    },
    {
        "id": "job-4",
        "title": "Full Stack Developer (MERN)",
        "company": "Cred",
        "location": "Bengaluru, India · Hybrid",
        "salary": "₹18 – 30 LPA",
        "type": "Full-time",
        "experience": "2-4 years",
        "posted": "3 days ago",
        "logo": "https://logo.clearbit.com/cred.club",
        "description": "Build premium financial products used by India's most creditworthy individuals. End-to-end ownership of Node + React features.",
        "skills": ["Node.js", "React", "MongoDB", "TypeScript", "AWS"],
        "requirements": [
            "Production experience with MERN stack",
            "Comfort with system design discussions",
            "Bias for action and clean code",
            "Past startup or scale-up experience preferred",
        ],
        "apply_url": "#",
    },
    {
        "id": "job-5",
        "title": "Data Science Associate",
        "company": "Flipkart",
        "location": "Bengaluru, India · On-site",
        "salary": "₹12 – 18 LPA",
        "type": "Full-time",
        "experience": "0-2 years",
        "posted": "Yesterday",
        "logo": "https://logo.clearbit.com/flipkart.com",
        "description": "Drive insights for India's largest e-commerce platform — from supply chain to customer growth. Work with petabyte-scale data.",
        "skills": ["Python", "SQL", "Pandas", "Tableau", "A/B Testing"],
        "requirements": [
            "Strong SQL and Python for analytics",
            "Statistics & experimentation fundamentals",
            "Communication skills to influence non-tech stakeholders",
            "Bachelor's in any quantitative field",
        ],
        "apply_url": "#",
    },
    {
        "id": "job-6",
        "title": "DevOps Engineer",
        "company": "Freshworks",
        "location": "Chennai, India · Remote",
        "salary": "₹16 – 26 LPA",
        "type": "Full-time",
        "experience": "2-5 years",
        "posted": "4 days ago",
        "logo": "https://logo.clearbit.com/freshworks.com",
        "description": "Own CI/CD, observability, and infrastructure-as-code for Freshworks's CX/CRM products serving 60K+ businesses globally.",
        "skills": ["AWS", "Kubernetes", "Terraform", "Docker", "Jenkins"],
        "requirements": [
            "Hands-on with managed Kubernetes (EKS/GKE)",
            "Infrastructure-as-Code experience (Terraform/Pulumi)",
            "Linux internals & networking basics",
            "Strong scripting (Bash/Python)",
        ],
        "apply_url": "#",
    },
]

SESSIONS = [
    {
        "id": "ses-1",
        "title": "Crack the Python Coding Interview",
        "mentor": "Aarav Sharma",
        "mentor_role": "SDE-2 at Google",
        "date": "2026-02-18",
        "time": "7:00 PM IST",
        "duration": "90 minutes",
        "seats_left": 12,
        "total_seats": 50,
        "price": "Free",
        "tags": ["Python", "DSA", "Interview Prep"],
        "thumbnail": "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=800&auto=format",
        "description": "Live mock interview followed by deep-dive into the most-asked Python questions at FAANG. Bring your laptop — we will code together.",
    },
    {
        "id": "ses-2",
        "title": "Build a Production-Ready React App",
        "mentor": "Sneha Iyer",
        "mentor_role": "Frontend Lead at Razorpay",
        "date": "2026-02-20",
        "time": "8:30 PM IST",
        "duration": "2 hours",
        "seats_left": 5,
        "total_seats": 40,
        "price": "₹299",
        "tags": ["React", "Frontend", "Production"],
        "thumbnail": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format",
        "description": "From folder structure to deployment — ship a real React app with auth, routing, state management, and error tracking by the end of the call.",
    },
    {
        "id": "ses-3",
        "title": "Machine Learning Roadmap 2026",
        "mentor": "Dr. Rohan Mehta",
        "mentor_role": "Senior Data Scientist at Microsoft",
        "date": "2026-02-22",
        "time": "6:00 PM IST",
        "duration": "75 minutes",
        "seats_left": 28,
        "total_seats": 100,
        "price": "Free",
        "tags": ["ML", "Career", "Roadmap"],
        "thumbnail": "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&auto=format",
        "description": "What to study, in what order, and how to land your first ML role — backed by hiring data from 200+ Indian tech companies.",
    },
    {
        "id": "ses-4",
        "title": "System Design Fundamentals",
        "mentor": "Vikram Iyengar",
        "mentor_role": "Principal Engineer at Atlassian",
        "date": "2026-02-25",
        "time": "9:00 PM IST",
        "duration": "2 hours",
        "seats_left": 18,
        "total_seats": 60,
        "price": "₹499",
        "tags": ["System Design", "Backend", "Senior"],
        "thumbnail": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format",
        "description": "Design Twitter, design Uber, design WhatsApp — walk away with a repeatable framework that works for any system design round.",
    },
    {
        "id": "ses-5",
        "title": "Resume + GitHub Review (1:1)",
        "mentor": "Priya Krishnan",
        "mentor_role": "Tech Recruiter, ex-Amazon",
        "date": "2026-02-19",
        "time": "Slots from 5 PM IST",
        "duration": "30 minutes (1:1)",
        "seats_left": 7,
        "total_seats": 20,
        "price": "₹199",
        "tags": ["Career", "Resume", "1:1"],
        "thumbnail": "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&auto=format",
        "description": "30-minute 1:1 review of your resume and GitHub. Walk away with concrete edits, project ideas, and a follow-up checklist.",
    },
    {
        "id": "ses-6",
        "title": "DSA Sprint: Trees & Graphs",
        "mentor": "Arjun Bhat",
        "mentor_role": "SDE-3 at Flipkart",
        "date": "2026-02-24",
        "time": "8:00 PM IST",
        "duration": "2.5 hours",
        "seats_left": 30,
        "total_seats": 80,
        "price": "Free",
        "tags": ["DSA", "Trees", "Graphs"],
        "thumbnail": "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format",
        "description": "Solve 12 hand-picked LeetCode hards live. Learn the patterns that show up again and again in coding rounds.",
    },
]

MENTORS = [
    {
        "id": "mentor-1",
        "name": "Aarav Sharma",
        "role": "SDE-2 at Google",
        "expertise": ["Python", "Algorithms", "System Design"],
        "experience": "6 years",
        "rating": 4.9,
        "sessions": 312,
        "bio": "Helped 500+ engineers crack their dream offers at FAANG and Indian unicorns.",
        "avatar": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format",
    },
    {
        "id": "mentor-2",
        "name": "Sneha Iyer",
        "role": "Frontend Lead at Razorpay",
        "expertise": ["React", "TypeScript", "UX Engineering"],
        "experience": "8 years",
        "rating": 4.95,
        "sessions": 248,
        "bio": "Shipped frontends used by 10M+ businesses. Loves design systems and micro-interactions.",
        "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format",
    },
    {
        "id": "mentor-3",
        "name": "Dr. Rohan Mehta",
        "role": "Senior Data Scientist at Microsoft",
        "expertise": ["Machine Learning", "NLP", "Deep Learning"],
        "experience": "10 years",
        "rating": 4.85,
        "sessions": 187,
        "bio": "PhD in ML, 30+ published papers, mentor at NPTEL & ACM India.",
        "avatar": "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&auto=format",
    },
    {
        "id": "mentor-4",
        "name": "Vikram Iyengar",
        "role": "Principal Engineer at Atlassian",
        "expertise": ["System Design", "Distributed Systems", "Java"],
        "experience": "14 years",
        "rating": 4.92,
        "sessions": 141,
        "bio": "Designed systems handling 1B+ requests/day. Open-source contributor to Apache projects.",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format",
    },
    {
        "id": "mentor-5",
        "name": "Priya Krishnan",
        "role": "Tech Recruiter, ex-Amazon",
        "expertise": ["Career Coaching", "Resume Review", "Interview Prep"],
        "experience": "9 years",
        "rating": 4.97,
        "sessions": 420,
        "bio": "Hired 1000+ engineers across Amazon, Microsoft, and Indian product startups.",
        "avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format",
    },
    {
        "id": "mentor-6",
        "name": "Arjun Bhat",
        "role": "SDE-3 at Flipkart",
        "expertise": ["DSA", "Competitive Programming", "Backend"],
        "experience": "7 years",
        "rating": 4.88,
        "sessions": 276,
        "bio": "Codeforces Grandmaster. Loves teaching the elegance hidden inside every algorithm.",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format",
    },
]